$(function(){
	$('#saas-home-center-ul').perfectScrollbar();
	$('#saas-home-left-ul').perfectScrollbar();
	$('#saas-home-right-ul').perfectScrollbar();
	$('#click_nav_1>ul').perfectScrollbar();
	$('#click_nav_2>ul').perfectScrollbar();
	$('#click_nav_3').perfectScrollbar();
	$(".window-right>div:nth-child(2)").perfectScrollbar();
	$(".mail-list-1").perfectScrollbar();
	$(".window-left").perfectScrollbar();
	$("#window-chat-right-invite>div:nth-child(3)").perfectScrollbar();
	$(".people-list").perfectScrollbar();
	$("#invite-group-colleague .colleague-list").perfectScrollbar();
	$("#invite-group-colleague").perfectScrollbar();
	$(".click-search-list").perfectScrollbar();
	$("#invite-group-crowd .crowd-ul").perfectScrollbar();
	$(".crowd-list").perfectScrollbar();
	$(".new-work-form-box").perfectScrollbar();
	$(".more ul").perfectScrollbar();
	$(".left-list-one ul").perfectScrollbar();
	$(".saas-right-content>ul>li>ul").perfectScrollbar();
	$("#chat_click_nav_1>ul").perfectScrollbar();
	$("#chat_click_nav_2>ul").perfectScrollbar();
	$("#chat_click_nav_3").perfectScrollbar();
	$(".left-list-two ul").perfectScrollbar();
	$(".saas-right-content>ul>li .ul-two-list").perfectScrollbar();
	$("#chat-right-invite>div:nth-child(3)").perfectScrollbar();
	$(".chat-search-list").perfectScrollbar();
	$(".work-content-1 .work-select ul").perfectScrollbar();
	$(".work-content-2 .work-select ul").perfectScrollbar();
	$(".work-content-3 .work-select-1 ul").perfectScrollbar();
	$(".work-content-3 .work-select-2 ul").perfectScrollbar();
	$(".work-content-1 .work-ul").perfectScrollbar();
	$(".work-content-2 .work-ul").perfectScrollbar();
	$(".work-content-3 .work-ul").perfectScrollbar();
	$(".work-form-box").perfectScrollbar();
	$(".saas-Schedule-content").perfectScrollbar();
	$(".week-data").perfectScrollbar();
	$(".Schedule-list").perfectScrollbar();
	$(".saas-unconfirmed").perfectScrollbar();
	$(".saas-Colleague-schedule").perfectScrollbar();
	$("#choose-workmate-colleague .choose-workmate-list").perfectScrollbar();
	$("#choose-workmate-colleague>ul").perfectScrollbar();
	$(".mail-list-2").perfectScrollbar();
	$(".staff-waitPacket-pepole").perfectScrollbar();
    $(".edit-under-ul").perfectScrollbar();
    $(".edit-checked").perfectScrollbar();
    $(".kind").perfectScrollbar();
	$(".controlBox").perfectScrollbar();
	$(".businessTrip-bottom-country").perfectScrollbar();
	$(".businessTrip-bottom-ChoiseCity").perfectScrollbar();
	$(".businessTrip-bottom-right >div").perfectScrollbar();
	$(".project-menu").perfectScrollbar();
	$(".cunction-srcoll > ul").perfectScrollbar();
	$(".set-order-list").perfectScrollbar();
	$(".standardConfiguration-moneyDetails-buttom").perfectScrollbar();
	$(".cityChiose-left").perfectScrollbar();
	$(".function-box-content-list > ul").perfectScrollbar();
	$(".spendingOnWaterCover").perfectScrollbar();
	$(".spendingOnWater-chioseCity-centerInput").perfectScrollbar();
	$(".businessDocument-list-bottom > ul").perfectScrollbar();
	$(".all-list").perfectScrollbar();
	$(".spendingOnWater-public-textarea").perfectScrollbar();
	$(".documentPublic-box-bottom").perfectScrollbar();
	$(".listBox > ul").perfectScrollbar();
	$(".professional-box > ul").perfectScrollbar();
	$(".professional-box1 > ul").perfectScrollbar();
	$(".tree-content").perfectScrollbar();
	$(".over-scroll-fit").perfectScrollbar();
	$(".expenditureEstablish-input > div").perfectScrollbar();
	$(".travelBookList-ul").perfectScrollbar();
	$(".travelBookList-ul-noGo").perfectScrollbar();
	$(".strokeFormulation-planeUl").perfectScrollbar();
	$(".people-con").perfectScrollbar();
	$(".person-city-coin-content2").perfectScrollbar();
	$(".person-city-coin-content3-content").perfectScrollbar();
	$(".reservationProcesse-listUl").perfectScrollbar();
	$(".add-class3").perfectScrollbar();
	$(".apply-day-alert-table > ul").perfectScrollbar();
	$(".allDepartment").perfectScrollbar();
	$(".slideOptionDown").perfectScrollbar();
	$(".Select-content-scroll").perfectScrollbar();
	$(".propertyReceipt-div > div").perfectScrollbar();
	$(".saas-left").perfectScrollbar();
	$(".examinationApprova-select > div > div").perfectScrollbar();
	$(".businessDocument-select > div > div").perfectScrollbar();
	$(".paymentExamine-search > div > div").perfectScrollbar();
	$(".settlePublic-list").perfectScrollbar();
	$(".report-content").perfectScrollbar();//	工作报告,我的日报弹窗
	$(".BookInformationContent-scroll").perfectScrollbar();
	$(".confirmPayment-bottom-list").perfectScrollbar();//	结算及支付,确认支付
	$(".informationQlist-scroll").perfectScrollbar();
	$(".AllStatTable ul").perfectScrollbar();
	//$(".AllStatTableDel").perfectScrollbar();
	$(".AllStatTableDel ul").perfectScrollbar();
	$(".edit-stan>ul").perfectScrollbar();//	员工管理,编辑－个人标准ul
	$(".CheckLs-scroll").perfectScrollbar();
});
